import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Web Developer",
    company: "PT. Presmas Digital Akademik",
    logo: "/images/careers/presmas.png",
    location: "Central java, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2025-1",
    end_date: null,
    industry: "academy",
    link: "#",
    // responsibilities: [
    //   "Developed and managed a portfolio website showcasing my best work and achievements as a Web Developer. The website emphasizes professional design and easy navigation for an optimal user experience",
    //   "Designed user interfaces with professional, responsive designs for both mobile and desktop devices, ensuring easy navigation for an optimal user experience",
    // ],
  },
  {
    position: "Frontend Web Developer",
    company: "Desa Wisata Antap Kec. wangon Kab. Banyumas",
    logo: "/images/careers/antap.png",
    location: "Banyumas, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2024-9",
    end_date: "2024-11",
    industry: "tourism",
    link: "#",
    responsibilities: [
      "Developed responsive and user-friendly web interfaces for Antap Tourism Village’s digital platform using HTML, CSS, JavaScript, and modern frontend frameworks.",
      "Collaborated with the design and backend teams to ensure seamless user experience and efficient integration of APIs and CMS content.",
      "Maintained and optimized website performance, ensuring compatibility across devices and browsers, with focus on accessibility and usability.",
      "Contributed to the visual branding and digital promotion efforts of the tourism village through interactive and engaging UI components.",
    ],
  },
  {
    position: "Team Reviewer Puspresnas",
    company: "Satria Muda Telkom University Purwokerto",
    logo: "/images/careers/satmud.png",
    location: "Central java, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2024-12",
    end_date: "2025-12",
    industry: "school",
    link: "#",
    responsibilities: [
      "Evaluated student project proposals for national programs (such as PKM and P2MW) based on innovation, feasibility, and academic impact.",
      "Provided structured feedback and recommendations to improve proposal quality, clarity, and alignment with Puspresnas standards.",
      "Collaborated with academic peers to ensure fair and consistent assessment across various fields of study.",
      "Strengthened critical thinking and academic writing analysis skills through engagement with diverse student submissions.",
    ],
  },
];
