import { ProjectItem } from "@/common/types/projects";

export const projectsData: ProjectItem[] = [
  {
    id: 1,
    title: "Website Portofolio Pertama",
    slug: "website-portofolio-pertama",
    description:
      "Website portofolio pertama yang dibuat menggunakan HTML CSS dan JavaScript untuk menampilkan project dan skill saya secara online",
    image: "/images/projects/web1.webp",
    link_demo: "https://hamkazainulardhi.github.io/web-porto/",
    link_github: "https://github.com/HamkaZainulArdhi/web-porto/",
    stacks: ["HTML", "CSS", "JS"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 2,
    title: "Filosofi Logo HUT RI ke 76 2024",
    slug: "filosofi-logo-hut-ri-ke-76-2024",
    description:
      "Website yang menjelaskan filosofi dan makna dari desain logo HUT RI ke 76 dengan tampilan interaktif menggunakan Bootstrap",
    image: "/images/projects/web2.webp",
    link_demo:
      "https://hamkazainulardhi.github.io/LOGO-HUT-RI-KE-79-CAKRAWALA-M-HAMKA-ZAINUL-ARDHI/",
    link_github:
      "https://github.com/HamkaZainulArdhi/LOGO-HUT-RI-KE-79-CAKRAWALA-M-HAMKA-ZAINUL-ARDHI",
    stacks: ["HTML", "CSS", "JS", "Bootstrap"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 3,
    title: "Animation Mountain Login Page",
    slug: "animation-mountain-login-page",
    description:
      "Halaman login dengan animasi gunung yang menarik dibuat menggunakan HTML CSS JavaScript dan Bootstrap untuk pengalaman user yang unik",
    image: "/images/projects/web3.webp",
    link_demo: "https://hamkazainulardhi.github.io/login-page-mtSUMBING/",
    link_github: "https://github.com/HamkaZainulArdhi/login-page-mtSUMBING",
    stacks: ["HTML", "CSS", "JS", "Bootstrap"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 4,
    title: "Sustainstyle",
    slug: "sustainstyle",
    description:
      "Platform fashion berkelanjutan yang dikembangkan dengan React.js Next.js dan TypeScript untuk mendukung industri fashion yang ramah lingkungan",
    image: "/images/projects/web4.webp",
    link_demo: "https://sustainstyle.vercel.app/",
    link_github: "https://github.com/HamkaZainulArdhi/Fashion-Web",
    stacks: ["TypeScript", "TailwindCSS", "React.js", "Next.js", "Npm"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 5,
    title: "Website Desa Wisata Antap",
    slug: "website-desa-wisata-antap",
    description:
      "Website promosi desa wisata Antap yang menampilkan destinasi wisata lokal dengan desain menarik menggunakan HTML CSS JavaScript Bootstrap",
    image: "/images/projects/web5.webp",
    link_demo: "https://desawisataantap.vercel.app/",
    link_github: "https://github.com/HamkaZainulArdhi/WISATA-ANTAP",
    stacks: ["HTML", "CSS", "JS", "Bootstrap"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 6,
    title: "Looping with PHP",
    slug: "looping-with-php",
    description:
      "Aplikasi PHP untuk demonstrasi looping dan pembuatan pola segitiga dengan database MySQL dan tampilan Bootstrap yang responsive",
    image: "/images/projects/web6.webp",
    link_demo: null,
    link_github:
      "https://github.com/HamkaZainulArdhi/LOOPING-SEGITIGA-ANTI-RIBET",
    stacks: ["PHP", "Bootstrap", "MySql"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 7,
    title: "Biorama Digitalisasi UMKM Purwokerto",
    slug: "biorama-digitalisasi-umkm-purwokerto",
    description:
      "Platform digitalisasi UMKM di Purwokerto untuk membantu usaha kecil menengah berkembang dengan teknologi modern dan organic placemaking",
    image: "/images/projects/web7.webp",
    link_demo: "https://biorama-organicplacemaking.vercel.app/",
    link_github: "https://github.com/HamkaZainulArdhi/TECHOPORIA.OI",
    stacks: ["HTML", "CSS", "JS", "TailwindCSS", "Npm"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 8,
    title: "HMSI-D Class Website At Tel-u",
    slug: "hmsi-d-class-website-at-tel-u",
    description:
      "Website resmi kelas HMSI-D Telkom University yang dikembangkan dengan React.js Next.js dan TypeScript untuk kebutuhan akademik mahasiswa",
    image: "/images/projects/web9.webp",
    link_demo: "https://hmsi-d.vercel.app/",
    link_github: "https://github.com/HamkaZainulArdhi/HMSI_D-website",
    stacks: ["TypeScript", "TailwindCSS", "React.js", "Next.js", "Npm"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 9,
    title: "Presmas (Internship)",
    slug: "presmas-internship",
    description:
      "Aplikasi CBT (Computer Based Test) yang dikembangkan selama magang di Presmas menggunakan React.js TypeScript dan MySQL database",
    image: "/images/projects/web10.webp",
    link_demo: "https://cbt.presmas.id/",
    link_github: null,
    stacks: ["TypeScript", "TailwindCSS", "React.js", "Vite", "MySql", "Npm"],
    content: null,
    is_show: true,
    is_featured: true,
  },
  {
    id: 10,
    title: "Hamka.site",
    slug: "hamka-site",
    description:
      "Website portofolio personal dengan fitur lengkap menggunakan Next.js TypeScript Supabase PostgreSQL dan Prisma ORM untuk manajemen konten",
    image: "/images/projects/web8.webp",
    link_demo: null,
    link_github: "https://github.com/HamkaZainulArdhi/site-porto",
    stacks: [
      "TypeScript",
      "TailwindCSS",
      "React.js",
      "Next.js",
      "Supabase",
      "PostgreSql",
      "Prisma",
      "Npm",
    ],
    content: null,
    is_show: true,
    is_featured: true,
  },
  {
    id: 11,
    title: "Telkom Publisher",
    slug: "telkom-publisher",
    description:
      "Aplikasi publisher digital untuk Telkom University menggunakan framework Laravel PHP dengan TailwindCSS dan database MySQL untuk manajemen konten",
    image: "/images/projects/web11.webp",
    link_demo: null,
    link_github: "https://github.com/HamkaZainulArdhi/Tugas-Besar",
    stacks: ["PHP", "TailwindCSS", "MySql", "Laravel"],
    content: null,
    is_show: true,
    is_featured: true,
  },
  {
    id: 12,
    title: "Fake Pengumuman SNBT 2025",
    slug: "fake-pengumuman-snbt-2025",
    description:
      "Website simulasi pengumuman SNBT 2025 yang dibuat untuk keperluan edukasi menggunakan HTML CSS JavaScript dan TailwindCSS framework",
    image: "/images/projects/web12.webp",
    link_demo: "https://fake-pengumuman-sbnt-2025-byzainard.vercel.app/",
    link_github:
      "https://github.com/HamkaZainulArdhi/FAKE-Pengumuman-SBNT-2025",
    stacks: ["HTML", "CSS", "JS", "TailwindCSS", "Npm"],
    content: null,
    is_show: true,
    is_featured: false,
  },
  {
    id: 13,
    title: "Dikdaya",
    slug: "Dikdaya",
    description:
      "Digitalisasi Peternakan kambing kelompok tani minda jaya dengan web app dan IOT",
    image: "/images/projects/web13.webp",
    link_demo: "https://dikdaya.com/",
    link_github: "",
    stacks: ["HTML", "CSS", "JS", "TailwindCSS", "Npm"],
    content: null,
    is_show: true,
    is_featured: true,
  },
  {
    id: 14,
    title: "Edited Spotify wrapped",
    slug: "Edited-Spotify-wrapped",
    description:
      "Membuat edited version dari Spotify Wrapped untuk menampilkan data musik favorit saya dengan desain yang sama dengan yang aslinya",
    image: "/images/projects/web14.webp",
    link_demo: "https://custom-spotify-wrappedmu.vercel.app/",
    link_github: "",
    stacks: ["TypeScript", "React.js", "TailwindCSS", "Npm"],
    content: null,
    is_show: true,
    is_featured: true,
  },
  {
    id: 15,
    title: "gizikita",
    slug: "gizikita",
    description:
      "Dengan dukungan AI Scanner, setiap menu MBG dapat diverifikasi kandungan gizinya, memastikan transparansi penyaluran dan kualitas asupan anak-anak Indonesia.",
    image: "/images/projects/web15.webp",
    link_demo: "https://mbg-gizikita.com/",
    link_github: "",
    stacks: ["TypeScript", "React.js", "TailwindCSS", "Npm", "Python"],
    content: null,
    is_show: true,
    is_featured: true,
  },
  {
    id: 16,
    title: "MBG Shield Admin Dashboard",
    slug: "mbg-shield-admin-dashboard",
    description:
      "MBG Shield Admin Dashboard adalah platform manajemen yang dirancang untuk memantau dan mengelola distribusi makanan bergizi MBG, memastikan setiap anak mendapatkan asupan yang tepat dengan dukungan data real-time dan analitik yang kuat.",
    image: "/images/projects/web16.webp",
    link_demo: "https://mbg-adminpanel.vercel.app/",
    link_github: "",
    stacks: ["TypeScript", "React.js", "TailwindCSS", "Npm", "Python"],
    content: null,
    is_show: true,
    is_featured: true,
  },
];
